name: react-unix-terminal-ci-cd

on: [push, pull_request]

jobs:
    all:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                threads:
                    - '4'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install PNPM
              run: |
                  sudo apt install npm
                  npm i --location=global pnpm

            - name: Install Depedencies
              run: pnpm installation

            - name: Run Linter
              run: pnpm lint

            - name: Run Format Check
              run: pnpm format-check

            - name: Run Tests
              env:
                  IS_CI: true
              run: pnpm test

            - name: Run Build
              run: pnpm build-prod
